config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :categories

  resources :items

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resource :session

  get 'about', to: 'pages#about'
  root 'pages#home'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_items
  has_many :items, throught: :category_items

  validates :title, presence: true
end

app/models/category_item.rb
class CategoryItem < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :category_items
  has_many :categories, through: :category_items

  validates :title, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :is_logged_in?
  before_action :current_user

  def current_user
    if is_logged_in?
      @current_user = (User.find(session[:user_id]) if session[:user_id].present?)

      @current_user
    end
  end

  def is_logged_in?
    session[:user_id].present?
  end

  def force_login
    unless is_logged_in?
      flash[:error] = "You are not logged in"
      redirect_to root_path
    end
  end



end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :force_login

  def index
    @items = if params[:q].present?
               Item.where('lower(title) LIKE ?', '%' + params[:q].downcase + '%')
             else
               Item.all
           end
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to items_path if is_logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @username = form_params[:username]
    @password = form_params[:password]
    @user = User.find_by(username: @username).try(:authenticate, @password)

    if @user.present?
      session[:user_id] = @user.id
      flash[:success] = 'You are now logged in!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    reset_session
    flash[:success] = 'You are now logged out!'
    redirect_to root_path
  end

  def form_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(form_params)

    if @user.save
      session[:user_id] = @user.id

      flash[:success] = 'Welcome to Source!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def form_params
    params.require(:user).permit(:name, :username, :email,
                                 :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def format_categories(categories)
    links = categories.map do |cat|
      link_to cat.title, category_path(cat)
    end

    links.to_sentence.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>
<% @categories.each do |cat| %>
  <p><%= link_to cat.title, category_path(cat) %></p>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

<p>
  <%= link_to "Back to all categories", categories_path %>
</p>


<div class="items-grid">
<%= render partial: "items/item", collection: @category.items.all %>

</div>
 

app/views/items/_item.html.erb
<div class="item">

<%= link_to item_path(item) do %>

  <h2><%= item.title %></h2>
  <%= image_tag item.image.medium %>
<% end %>


</div>

app/views/items/index.html.erb
<h1>Photo</h1>

<form action="">
  <input type="text" name="q" value="<%= params[:q] %>">
</form>

<div class="items-grid">
<%= render partial: "item", collection: @items %>

</div>

app/views/items/show.html.erb
<div class="item-page">


  <h1><%= @item.title %></h1>
  <p>
    <strong>Categories:</strong>
    <%= format_categories @item.categories %>
  </p>


    <%= simple_format @item.description %>

    <%= image_tag @item.image.medium %>

<p>
  <%= link_to "Download photo", @item.image.url, download: true %>
</p>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Source</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:success].present? %>
      <div class="success">
        <%= flash[:success] %>
      </div>
    <% end %>

    <% if flash[:error].present? %>
    <div class="error">
      <%= flash[:error] %>
    </div>
    <% end %>

      <header>
        <h1>Source
        </h1>

        <nav>
          <% if is_logged_in? %>
          <strong><%= @current_user.username %></strong>
          <%= link_to "All photos", items_path %>
          <%= link_to "Categories", categories_path %>
              <%= link_to "Log out", session_path, method: :delete %>
          <% else %>
          <% link_to "Sign up", new_user_path %>
          <% link_to "Log in", new_session_path %>
          <% end %>
        </nav>
      </header>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Source</h1>

<p>

  <%= link_to "Sign up", new_user_path, class: "button" %>
  <%= link_to "Log in", new_session_path, class: "button button-outline" %>

</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :name %>
  <%= f.input :username %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.button :submit %>
<% end %>